#!/usr/bin/env python
##
# @author Prahlad Yeri
# @email prahladyeri@yahoo.com
# @title Git hook for enforcing conventional commit spec
#
# @todo Create folder ~/.git-templates and set that value to init.templatedir git config key globally.
# @todo Copy this script to ~/.git-templates/hooks/ and rename it to commit-msg.
# @todo (Linux): Make the script executable.
import re
import argparse

examples = """+ 61c8ca9 fix: navbar not responsive on mobile
+ 479c48b test: prepared test cases for user authentication
+ a992020 chore: moved to semantic versioning
+ b818120 fix: button click even handler firing twice
+ c6e9a97 fix: login page css
+ dfdc715 feat(auth): added social login using twitter
"""

parser = argparse.ArgumentParser(
	description="Enforces conventional git commit messages.\nRead more at https://www.conventionalcommits.org/en/v1.0.0/")
parser.add_argument("filename", help="name of the file", type=str, )
args = parser.parse_args()

 pattern = r"(build|chore|ci|docs|feat|fix|style|refactor|revert|perf|test)(\([\w\_\-\.]+\))?:\s.*"

 with open(args.filename, 'r') as fp:
    commit_message = fp.read()

 result = re.match(pattern, commit_message)

 if not result:
    print("Please enter commit message in the conventional format and try to commit again. Examples:")
    print(examples)
    raise Exception("conventional commit validation failed")
